name: Test PHPStan5

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run:  cd apps/kita && composer install --prefer-dist --no-progress
      - name: Install phpstan
        run: composer require phpstan/phpstan

      - name: Run PHPStan
        run: cd apps/kita/vendor/bin && .\vendor\bin\phpstan -h